blank_issues_enabled: false
contact_links:
  - name: Please don't make blank issues with the name "sus"! It creates spam and we appreciate it if you chat with us in our Discord instead!
    url: https://discord.gg/k4d24VaAJN
    about: Visit our Discord
